trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - '*'
    exclude:
      - 'README.md'


variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 2.2
       
        - script: dotnet restore
       
        - task: DotNetCoreCLI@2
          displayName: 'Build Projects'
          inputs:
            command: build
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Run Tests'
          inputs:
            command: test
            projects: '**/*Test/*.csproj'
            arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'